// <auto-generated />
using System;
using EpicalCDI.Modules.Clinical.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EpicalCDI.Modules.Clinical.Migrations
{
    [DbContext(typeof(ClinicalDbContext))]
    partial class ClinicalDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("clinical")
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EpicalCDI.Modules.Clinical.Domain.Encounter", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("AdmitDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DischargeDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExternalEncounterId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("HospitalId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastUpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PatientExternalId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("HospitalId", "ExternalEncounterId")
                        .IsUnique();

                    b.ToTable("Encounters", "clinical");
                });

            modelBuilder.Entity("EpicalCDI.Modules.Clinical.Domain.Medication", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("EncounterId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("HashChecksum")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("HospitalId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastUpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MedicationName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EncounterId");

                    b.HasIndex("HospitalId", "EncounterId", "MedicationName", "StartTime")
                        .IsUnique();

                    b.ToTable("Medications", "clinical");
                });

            modelBuilder.Entity("EpicalCDI.Modules.Clinical.Domain.Observation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<long>("EncounterId")
                        .HasColumnType("bigint");

                    b.Property<string>("HashChecksum")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("HospitalId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastUpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ObservationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Unit")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EncounterId");

                    b.HasIndex("HospitalId", "EncounterId", "Code", "ObservationTime")
                        .IsUnique();

                    b.ToTable("Observations", "clinical");
                });

            modelBuilder.Entity("EpicalCDI.Modules.Clinical.Domain.Medication", b =>
                {
                    b.HasOne("EpicalCDI.Modules.Clinical.Domain.Encounter", null)
                        .WithMany("Medications")
                        .HasForeignKey("EncounterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EpicalCDI.Modules.Clinical.Domain.Observation", b =>
                {
                    b.HasOne("EpicalCDI.Modules.Clinical.Domain.Encounter", null)
                        .WithMany("Observations")
                        .HasForeignKey("EncounterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EpicalCDI.Modules.Clinical.Domain.Encounter", b =>
                {
                    b.Navigation("Medications");

                    b.Navigation("Observations");
                });
#pragma warning restore 612, 618
        }
    }
}
